In [1]:
import pandas as pd
import numpy as np

In [2]:
companies = pd.read_excel(
    "data/raw/companies.xlsx",
    header=1
)

balancesheet = pd.read_excel(
    "data/raw/balancesheet.xlsx",
    header=1
)

profitloss = pd.read_excel(
    "data/raw/profitandloss.xlsx",
    header=1
)

cashflow = pd.read_excel(
    "data/raw/cashflow.xlsx",
    header=1
)

ratios = pd.read_excel(
    "data/raw/financial_ratios.xlsx"
)

market = pd.read_excel(
    "data/raw/market_cap.xlsx"
)

In [3]:
print(companies.columns.tolist())

print(balancesheet.columns.tolist())

print(profitloss.columns.tolist())

print(cashflow.columns.tolist())

print(ratios.columns.tolist())

print(market.columns.tolist())

['id', 'company_logo', 'company_name', 'chart_link', 'about_company', 'website', 'nse_profile', 'bse_profile', 'face_value', 'book_value', 'roce_percentage', 'roe_percentage']
['id', 'company_id', 'year', 'equity_capital', 'reserves', 'borrowings', 'other_liabilities', 'total_liabilities', 'fixed_assets', 'cwip', 'investments', 'other_asset', 'total_assets']
['id', 'company_id', 'year', 'sales', 'expenses', 'operating_profit', 'opm_percentage', 'other_income', 'interest', 'depreciation', 'profit_before_tax', 'tax_percentage', 'net_profit', 'eps', 'dividend_payout']
['id', 'company_id', 'year', 'operating_activity', 'investing_activity', 'financing_activity', 'net_cash_flow']
['id', 'company_id', 'year', 'net_profit_margin_pct', 'operating_profit_margin_pct', 'return_on_equity_pct', 'debt_to_equity', 'interest_coverage', 'asset_turnover', 'free_cash_flow_cr', 'capex_cr', 'earnings_per_share', 'book_value_per_share', 'dividend_payout_ratio_pct', 'total_debt_cr', 'cash_from_operations_cr']
['id', 'company_id', 'year', 'market_cap_crore', 'enterprise_value_crore', 'pe_ratio', 'pb_ratio', 'ev_ebitda', 'dividend_yield_pct']

In [4]:
profitloss.columns.tolist()

['id',
 'company_id',
 'year',
 'sales',
 'expenses',
 'operating_profit',
 'opm_percentage',
 'other_income',
 'interest',
 'depreciation',
 'profit_before_tax',
 'tax_percentage',
 'net_profit',
 'eps',
 'dividend_payout']

In [5]:
cashflow.columns.tolist()

['id',
 'company_id',
 'year',
 'operating_activity',
 'investing_activity',
 'financing_activity',
 'net_cash_flow']

In [6]:
print(ratios.head())
print(ratios.columns.tolist())

   id company_id      year  net_profit_margin_pct  \
0   1        ABB  Dec 2012                   8.77
1   2        ABB  Mar 2014                   8.70
2   3        ABB  Mar 2014                   8.70
3   4        ABB  Mar 2015                  10.00
4   5        ABB  Mar 2015                  10.00

   operating_profit_margin_pct  return_on_equity_pct  debt_to_equity  \
0                         12.0                 22.41             0.0
1                         12.0                 25.13             0.0
2                         12.0                 25.13             0.0
3                         14.0                 24.44             0.0
4                         14.0                 24.44             0.0

   interest_coverage  asset_turnover  free_cash_flow_cr  capex_cr  \
0                NaN          1.8225               42.0      59.0
1                NaN          1.9982               11.0     144.0
2                NaN          1.9982                0.0       0.0
3                NaN          1.6659               28.0     187.0
4                NaN          1.6659            -1899.0    1864.0

   earnings_per_share  book_value_per_share  dividend_payout_ratio_pct  \
0                68.0                3.0810                       25.0
1                93.0                3.7524                       25.0
2                93.0                3.7524                       25.0
3               108.0                4.4619                       29.0
4               108.0                4.4619                       29.0

   total_debt_cr  cash_from_operations_cr
0              0                    101.0
1              0                    155.0
2              0                      0.0
3              0                    215.0
4              0                    -35.0
['id', 'company_id', 'year', 'net_profit_margin_pct', 'operating_profit_margin_pct', 'return_on_equity_pct', 'debt_to_equity', 'interest_coverage', 'asset_turnover', 'free_cash_flow_cr', 'capex_cr', 'earnings_per_share', 'book_value_per_share', 'dividend_payout_ratio_pct', 'total_debt_cr', 'cash_from_operations_cr']

In [7]:
print(companies.columns.tolist())

['id', 'company_logo', 'company_name', 'chart_link', 'about_company', 'website', 'nse_profile', 'bse_profile', 'face_value', 'book_value', 'roce_percentage', 'roe_percentage']

In [8]:
print(companies.head())

           id                                       company_logo  \
0         ABB   https://mkt.in/static/mkt-icons/nifty100/ABB.png
1  ADANIENSOL  https://m.economictimes.com/thumb/msid-1173715...
2    ADANIENT  https://mkt.in/static/mkt-icons/nifty100/ADANI...
3  ADANIGREEN  https://mkt.in/static/mkt-icons/nifty100/ADANI...
4  ADANIPORTS  https://mkt.in/static/mkt-icons/nifty100/ADANI...

                                company_name  \
0                           Abbott India Ltd
1                 Adani Energy Solutions Ltd
2                      Adani Enterprises Ltd
3                     Adani Green Energy Ltd
4  Adani Ports & Special Economic Zone Ltd\n

                                          chart_link  \
0  https://in.tradingview.com/chart/?symbol=NSE%3...
1  https://in.tradingview.com/chart/?symbol=NSE%3...
2  https://in.tradingview.com/chart/?symbol=ADANIENT
3  https://in.tradingview.com/chart/?symbol=NSE%3...
4  https://in.tradingview.com/chart/?symbol=NSE%3...

                                       about_company  \
0  Abbott India Ltd is one of the leading multina...
1  AESL, part of the Adani portfolio, is a multid...
2  Adani Enterprises Ltd is an Indian multination...
3  Adani Green Energy Limited, incorporated in 20...
4  Adani Ports & Special Economic Zone is in the ...

                                 website  \
0              https://www.abbott.co.in/
1  https://www.adanienergysolutions.com/
2      https://www.adanienterprises.com/
3       http://www.adanigreenenergy.com/
4             http://www.adaniports.com/

                                         nse_profile  \
0  https://www.nseindia.com/get-quotes/equity?sym...
1  https://www.nseindia.com/get-quotes/equity?sym...
2  https://www.nseindia.com/get-quotes/equity?sym...
3  https://www.nseindia.com/get-quotes/equity?sym...
4  https://www.nseindia.com/get-quotes/equity?sym...

                                         bse_profile  face_value  book_value  \
0  https://www.bseindia.com/stock-share-price/abb...        10.0      1657.0
1  https://www.bseindia.com/stock-share-price/ada...        10.0       175.0
2  https://www.bseindia.com/stock-share-price/ada...         1.0       363.0
3  https://www.bseindia.com/stock-share-price/ada...        10.0        67.0
4  https://www.bseindia.com/stock-share-price/ada...         2.0       265.0

   roce_percentage  roe_percentage
0             46.0           34.90
1              9.0            8.59
2             11.6           13.64
3             96.5           14.70
4             12.9           18.10

In [9]:
print(ratios.columns[:10])

print(market.columns[:10])

print(profitloss.columns[:10])

print(balancesheet.columns[:10])

print(cashflow.columns[:10])

print(companies.columns)

Index(['id', 'company_id', 'year', 'net_profit_margin_pct',
       'operating_profit_margin_pct', 'return_on_equity_pct', 'debt_to_equity',
       'interest_coverage', 'asset_turnover', 'free_cash_flow_cr'],
      dtype='object')
Index(['id', 'company_id', 'year', 'market_cap_crore',
       'enterprise_value_crore', 'pe_ratio', 'pb_ratio', 'ev_ebitda',
       'dividend_yield_pct'],
      dtype='object')
Index(['id', 'company_id', 'year', 'sales', 'expenses', 'operating_profit',
       'opm_percentage', 'other_income', 'interest', 'depreciation'],
      dtype='object')
Index(['id', 'company_id', 'year', 'equity_capital', 'reserves', 'borrowings',
       'other_liabilities', 'total_liabilities', 'fixed_assets', 'cwip'],
      dtype='object')
Index(['id', 'company_id', 'year', 'operating_activity', 'investing_activity',
       'financing_activity', 'net_cash_flow'],
      dtype='object')
Index(['id', 'company_logo', 'company_name', 'chart_link', 'about_company',
       'website', 'nse_profile', 'bse_profile', 'face_value', 'book_value',
       'roce_percentage', 'roe_percentage'],
      dtype='object')

In [10]:
print(companies[["id", "company_name"]].head())

           id                               company_name
0         ABB                           Abbott India Ltd
1  ADANIENSOL                 Adani Energy Solutions Ltd
2    ADANIENT                      Adani Enterprises Ltd
3  ADANIGREEN                     Adani Green Energy Ltd
4  ADANIPORTS  Adani Ports & Special Economic Zone Ltd\n

In [11]:
print(ratios["year"].head())

print(balancesheet["year"].head())

print(profitloss["year"].head())

print(cashflow["year"].head())

print(market["year"].head())

0    Dec 2012
1    Mar 2014
2    Mar 2014
3    Mar 2015
4    Mar 2015
Name: year, dtype: object
0    Dec 2012
1    Mar 2014
2    Mar 2015
3    Mar 2016
4    Mar 2017
Name: year, dtype: object
0    Dec 2012
1    Mar 2014
2    Mar 2015
3    Mar 2016
4    Mar 2017
Name: year, dtype: object
0    Mar-13
1    Mar-14
2    Mar-15
3    Mar-16
4    Mar-17
Name: year, dtype: object
0    2019
1    2020
2    2021
3    2022
4    2023
Name: year, dtype: int64

In [12]:
print(balancesheet["year"].head(10))
print(profitloss["year"].head(10))
print(cashflow["year"].head(10))
print(ratios["year"].head(10))
print(market["year"].head(10))

0    Dec 2012
1    Mar 2014
2    Mar 2015
3    Mar 2016
4    Mar 2017
5    Mar 2018
6    Mar 2019
7    Mar 2020
8    Mar 2021
9    Mar 2022
Name: year, dtype: object
0    Dec 2012
1    Mar 2014
2    Mar 2015
3    Mar 2016
4    Mar 2017
5    Mar 2018
6    Mar 2019
7    Mar 2020
8    Mar 2021
9    Mar 2022
Name: year, dtype: object
0    Mar-13
1    Mar-14
2    Mar-15
3    Mar-16
4    Mar-17
5    Mar-18
6    Mar-19
7    Mar-20
8    Mar-21
9    Mar-22
Name: year, dtype: object
0    Dec 2012
1    Mar 2014
2    Mar 2014
3    Mar 2015
4    Mar 2015
5    Mar 2016
6    Mar 2016
7    Mar 2017
8    Mar 2017
9    Mar 2018
Name: year, dtype: object
0    2019
1    2020
2    2021
3    2022
4    2023
5    2024
6    2019
7    2020
8    2021
9    2022
Name: year, dtype: int64

In [13]:
import re

def extract_year(x):
    if pd.isna(x):
        return None

    x = str(x)

    # Find a 4-digit year first
    m = re.search(r"(20\d{2})", x)
    if m:
        return int(m.group(1))

    # Otherwise handle trailing 2-digit years
    m = re.search(r"(\d{2})$", x)
    if m:
        yy = int(m.group(1))
        return 2000 + yy

    return None

for df in [balancesheet, profitloss, cashflow, ratios, market]:
    df["year"] = df["year"].apply(extract_year)

In [14]:
print(balancesheet["year"].head())
print(profitloss["year"].head())
print(cashflow["year"].head())
print(ratios["year"].head())
print(market["year"].head())

0    2012
1    2014
2    2015
3    2016
4    2017
Name: year, dtype: int64
0    2012.0
1    2014.0
2    2015.0
3    2016.0
4    2017.0
Name: year, dtype: float64
0    2013
1    2014
2    2015
3    2016
4    2017
Name: year, dtype: int64
0    2012
1    2014
2    2014
3    2015
4    2015
Name: year, dtype: int64
0    2019
1    2020
2    2021
3    2022
4    2023
Name: year, dtype: int64

In [15]:
# Remove unnecessary primary key columns

ratios = ratios.drop(columns=["id"], errors="ignore")
market = market.drop(columns=["id"], errors="ignore")
balancesheet = balancesheet.drop(columns=["id"], errors="ignore")
profitloss = profitloss.drop(columns=["id"], errors="ignore")
cashflow = cashflow.drop(columns=["id"], errors="ignore")

In [16]:
print(ratios.columns)
print(market.columns)
print(balancesheet.columns)
print(profitloss.columns)
print(cashflow.columns)

Index(['company_id', 'year', 'net_profit_margin_pct',
       'operating_profit_margin_pct', 'return_on_equity_pct', 'debt_to_equity',
       'interest_coverage', 'asset_turnover', 'free_cash_flow_cr', 'capex_cr',
       'earnings_per_share', 'book_value_per_share',
       'dividend_payout_ratio_pct', 'total_debt_cr',
       'cash_from_operations_cr'],
      dtype='object')
Index(['company_id', 'year', 'market_cap_crore', 'enterprise_value_crore',
       'pe_ratio', 'pb_ratio', 'ev_ebitda', 'dividend_yield_pct'],
      dtype='object')
Index(['company_id', 'year', 'equity_capital', 'reserves', 'borrowings',
       'other_liabilities', 'total_liabilities', 'fixed_assets', 'cwip',
       'investments', 'other_asset', 'total_assets'],
      dtype='object')
Index(['company_id', 'year', 'sales', 'expenses', 'operating_profit',
       'opm_percentage', 'other_income', 'interest', 'depreciation',
       'profit_before_tax', 'tax_percentage', 'net_profit', 'eps',
       'dividend_payout'],
      dtype='object')
Index(['company_id', 'year', 'operating_activity', 'investing_activity',
       'financing_activity', 'net_cash_flow'],
      dtype='object')

In [17]:
master = (
    ratios
    .merge(market, on=["company_id", "year"], how="left")
    .merge(profitloss, on=["company_id", "year"], how="left")
    .merge(balancesheet, on=["company_id", "year"], how="left")
    .merge(cashflow, on=["company_id", "year"], how="left")
    .merge(
        companies[["id", "company_name"]],
        left_on="company_id",
        right_on="id",
        how="left"
    )
)

master = master.drop(columns=["id"], errors="ignore")

print(master.shape)
master.head()

(1679, 48)

,company_id,year,net_profit_margin_pct,operating_profit_margin_pct,return_on_equity_pct,debt_to_equity,interest_coverage,asset_turnover,free_cash_flow_cr,capex_cr,...,fixed_assets,cwip,investments,other_asset,total_assets,operating_activity,investing_activity,financing_activity,net_cash_flow,company_name
0,ABB,2012,8.77,12.0,22.41,0.0,NaN,1.8225,42.0,59.0,...,109,1,0,798,907,101.0,-59.0,-42.0,1.0,Abbott India Ltd
1,ABB,2014,8.70,12.0,25.13,0.0,NaN,1.9982,11.0,144.0,...,98,1,0,1040,1139,155.0,-144.0,-42.0,-31.0,Abbott India Ltd
2,ABB,2014,8.70,12.0,25.13,0.0,NaN,1.9982,11.0,144.0,...,98,1,0,1040,1139,0.0,0.0,0.0,0.0,Abbott India Ltd
3,ABB,2014,8.70,12.0,25.13,0.0,NaN,1.9982,0.0,0.0,...,98,1,0,1040,1139,155.0,-144.0,-42.0,-31.0,Abbott India Ltd
4,ABB,2014,8.70,12.0,25.13,0.0,NaN,1.9982,0.0,0.0,...,98,1,0,1040,1139,0.0,0.0,0.0,0.0,Abbott India Ltd

In [18]:
print(master.shape)
master.head()

(1679, 48)

,company_id,year,net_profit_margin_pct,operating_profit_margin_pct,return_on_equity_pct,debt_to_equity,interest_coverage,asset_turnover,free_cash_flow_cr,capex_cr,...,fixed_assets,cwip,investments,other_asset,total_assets,operating_activity,investing_activity,financing_activity,net_cash_flow,company_name
0,ABB,2012,8.77,12.0,22.41,0.0,NaN,1.8225,42.0,59.0,...,109,1,0,798,907,101.0,-59.0,-42.0,1.0,Abbott India Ltd
1,ABB,2014,8.70,12.0,25.13,0.0,NaN,1.9982,11.0,144.0,...,98,1,0,1040,1139,155.0,-144.0,-42.0,-31.0,Abbott India Ltd
2,ABB,2014,8.70,12.0,25.13,0.0,NaN,1.9982,11.0,144.0,...,98,1,0,1040,1139,0.0,0.0,0.0,0.0,Abbott India Ltd
3,ABB,2014,8.70,12.0,25.13,0.0,NaN,1.9982,0.0,0.0,...,98,1,0,1040,1139,155.0,-144.0,-42.0,-31.0,Abbott India Ltd
4,ABB,2014,8.70,12.0,25.13,0.0,NaN,1.9982,0.0,0.0,...,98,1,0,1040,1139,0.0,0.0,0.0,0.0,Abbott India Ltd

In [19]:
import os

os.makedirs("../data/processed", exist_ok=True)

master.to_csv("../data/processed/master_dataset.csv", index=False)

print("Saved!")

Saved!

In [20]:
print("Ratios      :", ratios["year"].dtype)
print("Market      :", market["year"].dtype)
print("ProfitLoss  :", profitloss["year"].dtype)
print("BalanceSheet:", balancesheet["year"].dtype)
print("CashFlow    :", cashflow["year"].dtype)

Ratios      : int64
Market      : int64
ProfitLoss  : float64
BalanceSheet: int64
CashFlow    : int64

In [21]:
# Convert year column to integer in every dataframe

for df in [ratios, market, profitloss, balancesheet, cashflow]:
    df = df[df["year"].notna()]
    df["year"] = df["year"].astype(int)

/var/folders/wq/qjtlzxqd7230xkvd70xf0jdr0000gn/T/ipykernel_2782/29149226.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["year"] = df["year"].astype(int)

In [22]:
# Remove unnecessary id columns before merging
ratios = ratios.drop(columns=["id"], errors="ignore")
market = market.drop(columns=["id"], errors="ignore")
profitloss = profitloss.drop(columns=["id"], errors="ignore")
balancesheet = balancesheet.drop(columns=["id"], errors="ignore")
cashflow = cashflow.drop(columns=["id"], errors="ignore")

# Merge datasets
master = (
    ratios
    .merge(market, on=["company_id", "year"], how="left")
    .merge(profitloss, on=["company_id", "year"], how="left")
    .merge(balancesheet, on=["company_id", "year"], how="left")
    .merge(cashflow, on=["company_id", "year"], how="left")
    .merge(
        companies[["id", "company_name"]],
        left_on="company_id",
        right_on="id",
        how="left"
    )
)

# Remove the company id duplicate created by the last merge
master.drop(columns=["id"], inplace=True)

print(master.shape)
master.head()

(1679, 48)

,company_id,year,net_profit_margin_pct,operating_profit_margin_pct,return_on_equity_pct,debt_to_equity,interest_coverage,asset_turnover,free_cash_flow_cr,capex_cr,...,fixed_assets,cwip,investments,other_asset,total_assets,operating_activity,investing_activity,financing_activity,net_cash_flow,company_name
0,ABB,2012,8.77,12.0,22.41,0.0,NaN,1.8225,42.0,59.0,...,109,1,0,798,907,101.0,-59.0,-42.0,1.0,Abbott India Ltd
1,ABB,2014,8.70,12.0,25.13,0.0,NaN,1.9982,11.0,144.0,...,98,1,0,1040,1139,155.0,-144.0,-42.0,-31.0,Abbott India Ltd
2,ABB,2014,8.70,12.0,25.13,0.0,NaN,1.9982,11.0,144.0,...,98,1,0,1040,1139,0.0,0.0,0.0,0.0,Abbott India Ltd
3,ABB,2014,8.70,12.0,25.13,0.0,NaN,1.9982,0.0,0.0,...,98,1,0,1040,1139,155.0,-144.0,-42.0,-31.0,Abbott India Ltd
4,ABB,2014,8.70,12.0,25.13,0.0,NaN,1.9982,0.0,0.0,...,98,1,0,1040,1139,0.0,0.0,0.0,0.0,Abbott India Ltd

In [23]:
import os

os.makedirs("data/processed", exist_ok=True)

master.to_csv(
    "data/processed/master_dataset.csv",
    index=False
)

print("Saved successfully!")
print(os.path.abspath("data/processed/master_dataset.csv"))

Saved successfully!
/Users/shivanshkhanna/Documents/nifty100_project/data/processed/master_dataset.csv

In [24]:
import os

print(os.listdir("data/processed"))

['master_dataset.csv', 'final_company_rankings.csv', 'peer_percentiles.csv', 'nifty100_kpi_scores.csv']

In [25]:
peer = pd.read_excel(
    "data/raw/peer_groups.xlsx",
    header=1
)

peer = peer.rename(
    columns={
        "peer_group": "peer_group"
    }
)

In [26]:
peer = pd.read_excel(
    "data/raw/peer_groups.xlsx"
)

In [27]:
print(peer.columns)

Index(['id', 'peer_group_name', 'company_id', 'is_benchmark'], dtype='object')

In [28]:
master = master.merge(
    peer[["company_id", "peer_group_name"]],
    on="company_id",
    how="left"
)

In [29]:
master.columns.tolist()

['company_id',
 'year',
 'net_profit_margin_pct',
 'operating_profit_margin_pct',
 'return_on_equity_pct',
 'debt_to_equity',
 'interest_coverage',
 'asset_turnover',
 'free_cash_flow_cr',
 'capex_cr',
 'earnings_per_share',
 'book_value_per_share',
 'dividend_payout_ratio_pct',
 'total_debt_cr',
 'cash_from_operations_cr',
 'market_cap_crore',
 'enterprise_value_crore',
 'pe_ratio',
 'pb_ratio',
 'ev_ebitda',
 'dividend_yield_pct',
 'sales',
 'expenses',
 'operating_profit',
 'opm_percentage',
 'other_income',
 'interest',
 'depreciation',
 'profit_before_tax',
 'tax_percentage',
 'net_profit',
 'eps',
 'dividend_payout',
 'equity_capital',
 'reserves',
 'borrowings',
 'other_liabilities',
 'total_liabilities',
 'fixed_assets',
 'cwip',
 'investments',
 'other_asset',
 'total_assets',
 'operating_activity',
 'investing_activity',
 'financing_activity',
 'net_cash_flow',
 'company_name',
 'peer_group_name']

In [30]:
master = pd.read_csv("data/processed/master_dataset.csv")
print(master.columns.tolist())

['company_id', 'year', 'net_profit_margin_pct', 'operating_profit_margin_pct', 'return_on_equity_pct', 'debt_to_equity', 'interest_coverage', 'asset_turnover', 'free_cash_flow_cr', 'capex_cr', 'earnings_per_share', 'book_value_per_share', 'dividend_payout_ratio_pct', 'total_debt_cr', 'cash_from_operations_cr', 'market_cap_crore', 'enterprise_value_crore', 'pe_ratio', 'pb_ratio', 'ev_ebitda', 'dividend_yield_pct', 'sales', 'expenses', 'operating_profit', 'opm_percentage', 'other_income', 'interest', 'depreciation', 'profit_before_tax', 'tax_percentage', 'net_profit', 'eps', 'dividend_payout', 'equity_capital', 'reserves', 'borrowings', 'other_liabilities', 'total_liabilities', 'fixed_assets', 'cwip', 'investments', 'other_asset', 'total_assets', 'operating_activity', 'investing_activity', 'financing_activity', 'net_cash_flow', 'company_name']

In [31]:
peer = pd.read_excel(
    "data/raw/peer_groups.xlsx"
)

print(peer.columns)

Index(['id', 'peer_group_name', 'company_id', 'is_benchmark'], dtype='object')

In [32]:
master["company_id"] = master["company_id"].astype(str).str.strip()

peer["company_id"] = peer["company_id"].astype(str).str.strip()

In [33]:

master = master.merge(

    peer[
        [
            "company_id",
            "peer_group_name",
            "is_benchmark"
        ]
    ],

    on="company_id",

    how="left"

)

In [34]:
print(master.columns.tolist())

['company_id', 'year', 'net_profit_margin_pct', 'operating_profit_margin_pct', 'return_on_equity_pct', 'debt_to_equity', 'interest_coverage', 'asset_turnover', 'free_cash_flow_cr', 'capex_cr', 'earnings_per_share', 'book_value_per_share', 'dividend_payout_ratio_pct', 'total_debt_cr', 'cash_from_operations_cr', 'market_cap_crore', 'enterprise_value_crore', 'pe_ratio', 'pb_ratio', 'ev_ebitda', 'dividend_yield_pct', 'sales', 'expenses', 'operating_profit', 'opm_percentage', 'other_income', 'interest', 'depreciation', 'profit_before_tax', 'tax_percentage', 'net_profit', 'eps', 'dividend_payout', 'equity_capital', 'reserves', 'borrowings', 'other_liabilities', 'total_liabilities', 'fixed_assets', 'cwip', 'investments', 'other_asset', 'total_assets', 'operating_activity', 'investing_activity', 'financing_activity', 'net_cash_flow', 'company_name', 'peer_group_name', 'is_benchmark']

In [35]:
master[
    [
        "company_name",
        "company_id",
        "peer_group_name"
    ]
].head()

       company_name company_id peer_group_name
0  Abbott India Ltd        ABB             NaN
1  Abbott India Ltd        ABB             NaN
2  Abbott India Ltd        ABB             NaN
3  Abbott India Ltd        ABB             NaN
4  Abbott India Ltd        ABB             NaN

In [36]:
print(master["company_id"].head(10).tolist())
print(peer["company_id"].head(10).tolist())

['ABB', 'ABB', 'ABB', 'ABB', 'ABB', 'ABB', 'ABB', 'ABB', 'ABB', 'ABB']
['HDFCBANK', 'ICICIBANK', 'AXISBANK', 'KOTAKBANK', 'INDUSINDBK', 'SBIN', 'BANKBARODA', 'CANBK', 'PNB', 'TCS']

In [37]:
print(master["company_id"].dtype)
print(peer["company_id"].dtype)

object
object

In [38]:
common = set(master["company_id"].astype(str).str.strip()) & set(peer["company_id"].astype(str).str.strip())

print("Common IDs:", len(common))
print("Sample:", list(common)[:10])

Common IDs: 55
Sample: ['HINDALCO', 'TATAPOWER', 'BAJFINANCE', 'JSWSTEEL', 'TORNTPHARM', 'BPCL', 'NTPC', 'SBILIFE', 'BAJAJ-AUTO', 'TATAMOTORS']

In [39]:
master[
    master["peer_group_name"].notna()
][["company_id", "company_name", "peer_group_name"]].head(20)

     company_id            company_name    peer_group_name
74   ADANIGREEN  Adani Green Energy Ltd  Power & Utilities
75   ADANIGREEN  Adani Green Energy Ltd  Power & Utilities
76   ADANIGREEN  Adani Green Energy Ltd  Power & Utilities
77   ADANIGREEN  Adani Green Energy Ltd  Power & Utilities
78   ADANIGREEN  Adani Green Energy Ltd  Power & Utilities
79   ADANIGREEN  Adani Green Energy Ltd  Power & Utilities
80   ADANIGREEN  Adani Green Energy Ltd  Power & Utilities
81   ADANIGREEN  Adani Green Energy Ltd  Power & Utilities
82   ADANIGREEN  Adani Green Energy Ltd  Power & Utilities
135  ADANIPOWER         Adani Power Ltd  Power & Utilities
136  ADANIPOWER         Adani Power Ltd  Power & Utilities
137  ADANIPOWER         Adani Power Ltd  Power & Utilities
138  ADANIPOWER         Adani Power Ltd  Power & Utilities
139  ADANIPOWER         Adani Power Ltd  Power & Utilities
140  ADANIPOWER         Adani Power Ltd  Power & Utilities
141  ADANIPOWER         Adani Power Ltd  Power & Utilities
142  ADANIPOWER         Adani Power Ltd  Power & Utilities
143  ADANIPOWER         Adani Power Ltd  Power & Utilities
144  ADANIPOWER         Adani Power Ltd  Power & Utilities
145  ADANIPOWER         Adani Power Ltd  Power & Utilities

In [40]:
master.to_csv(
    "data/processed/master_dataset.csv",
    index=False
)

print("master_dataset.csv updated successfully")

master_dataset.csv updated successfully

In [41]:
saved = pd.read_csv("data/processed/master_dataset.csv")

print(saved.columns.tolist())
print(saved["peer_group_name"].notna().sum())

['company_id', 'year', 'net_profit_margin_pct', 'operating_profit_margin_pct', 'return_on_equity_pct', 'debt_to_equity', 'interest_coverage', 'asset_turnover', 'free_cash_flow_cr', 'capex_cr', 'earnings_per_share', 'book_value_per_share', 'dividend_payout_ratio_pct', 'total_debt_cr', 'cash_from_operations_cr', 'market_cap_crore', 'enterprise_value_crore', 'pe_ratio', 'pb_ratio', 'ev_ebitda', 'dividend_yield_pct', 'sales', 'expenses', 'operating_profit', 'opm_percentage', 'other_income', 'interest', 'depreciation', 'profit_before_tax', 'tax_percentage', 'net_profit', 'eps', 'dividend_payout', 'equity_capital', 'reserves', 'borrowings', 'other_liabilities', 'total_liabilities', 'fixed_assets', 'cwip', 'investments', 'other_asset', 'total_assets', 'operating_activity', 'investing_activity', 'financing_activity', 'net_cash_flow', 'company_name', 'peer_group_name', 'is_benchmark']
1111

In [42]:
import pandas as pd

market = pd.read_excel("data/raw/market_cap.xlsx")

print(market.columns.tolist())

market.head()

['id', 'company_id', 'year', 'market_cap_crore', 'enterprise_value_crore', 'pe_ratio', 'pb_ratio', 'ev_ebitda', 'dividend_yield_pct']

,id,company_id,year,market_cap_crore,enterprise_value_crore,pe_ratio,pb_ratio,ev_ebitda,dividend_yield_pct
0,1,ABB,2019,844312.98,814410.48,19.29,14.26,22.84,0.84
1,2,ABB,2020,923674.33,1120679.72,67.54,13.03,24.93,3.90
2,3,ABB,2021,1020674.09,1166450.81,62.63,6.67,7.58,1.58
3,4,ABB,2022,1185994.82,1158637.42,18.68,4.75,6.12,3.35
4,5,ABB,2023,1161513.28,1103083.77,58.34,12.72,5.70,1.05

In [43]:
%run src/analytics/valuation.py

/Users/shivanshkhanna/Documents/nifty100_project/src/analytics/valuation.py:124: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  valuation.rename(

valuation_summary.xlsx created
valuation_flags.csv created

In [44]:
import pandas as pd

analysis = pd.read_excel("data/raw/analysis.xlsx")

print(analysis.columns.tolist())
print(analysis.head())

['Bluestock Fintech — Nifty 100  |  Analysis  |  20 records', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5']
  Bluestock Fintech — Nifty 100  |  Analysis  |  20 records  Unnamed: 1  \
0                                                 id         company_id
1                                                  1           HDFCBANK
2                                                 10            SBILIFE
3                                                 11            SBILIFE
4                                                 12            SBILIFE

                Unnamed: 2                Unnamed: 3  \
0  compounded_sales_growth  compounded_profit_growth
1            10 Years: 21%             10 Years: 22%
2       5 Years:       24%    5 Years:            6%
3       3 Years:       17%    3 Years:            9%
4      TTM:            43%  TTM:                 18%

                 Unnamed: 4            Unnamed: 5
0          stock_price_cagr                   roe
1         10 Years:     15%     10 Years:     17%
2         5 Years:       8%  5 Years          14%
3         3 Years:       7%  3 Years:         13%
4       1 Year:         -2%   Last Year:      12%

In [45]:
import pandas as pd

master = pd.read_csv("data/processed/master_dataset.csv")

print(master.columns.tolist())

['company_id', 'year', 'net_profit_margin_pct', 'operating_profit_margin_pct', 'return_on_equity_pct', 'debt_to_equity', 'interest_coverage', 'asset_turnover', 'free_cash_flow_cr', 'capex_cr', 'earnings_per_share', 'book_value_per_share', 'dividend_payout_ratio_pct', 'total_debt_cr', 'cash_from_operations_cr', 'market_cap_crore', 'enterprise_value_crore', 'pe_ratio', 'pb_ratio', 'ev_ebitda', 'dividend_yield_pct', 'sales', 'expenses', 'operating_profit', 'opm_percentage', 'other_income', 'interest', 'depreciation', 'profit_before_tax', 'tax_percentage', 'net_profit', 'eps', 'dividend_payout', 'equity_capital', 'reserves', 'borrowings', 'other_liabilities', 'total_liabilities', 'fixed_assets', 'cwip', 'investments', 'other_asset', 'total_assets', 'operating_activity', 'investing_activity', 'financing_activity', 'net_cash_flow', 'company_name', 'peer_group_name', 'is_benchmark']

In [46]:
master.groupby("company_id").size().head()

company_id
ABB           49
ADANIENSOL    12
ADANIENT      13
ADANIGREEN     9
ADANIPORTS    52
dtype: int64

In [47]:
import pandas as pd

master = pd.read_csv("data/processed/master_dataset.csv")

required = [
    "company_id",
    "year",
    "sales",
    "net_profit",
    "free_cash_flow_cr",
    "cash_from_operations_cr",
    "operating_activity",
    "investing_activity",
    "financing_activity",
    "borrowings"
]

for col in required:
    print(f"{col}: {col in master.columns}")

company_id: True
year: True
sales: True
net_profit: True
free_cash_flow_cr: True
cash_from_operations_cr: True
operating_activity: True
investing_activity: True
financing_activity: True
borrowings: True

In [48]:
master[[
    "company_id",
    "year",
    "sales",
    "net_profit",
    "free_cash_flow_cr",
    "cash_from_operations_cr",
    "operating_activity",
    "investing_activity",
    "financing_activity",
    "borrowings"
]].head()

,company_id,year,sales,net_profit,free_cash_flow_cr,cash_from_operations_cr,operating_activity,investing_activity,financing_activity,borrowings
0,ABB,2012,1653,145,42.0,101.0,101.0,-59.0,-42.0,0
1,ABB,2014,2276,198,11.0,155.0,155.0,-144.0,-42.0,0
2,ABB,2014,2276,198,11.0,155.0,0.0,0.0,0.0,0
3,ABB,2014,2276,198,0.0,0.0,155.0,-144.0,-42.0,0
4,ABB,2014,2276,198,0.0,0.0,0.0,0.0,0.0,0

In [49]:
print(master["year"].unique()[:20])

print(master["capex_cr"].head())

print(master["capex_cr"].isna().sum())

[2012 2014 2015 2016 2017 2018 2019 2020 2021 2022 2023 2024 2013 2011]
0     59.0
1    144.0
2    144.0
3      0.0
4      0.0
Name: capex_cr, dtype: float64
2

In [50]:
master = pd.read_csv("data/processed/master_dataset.csv")

print(master["company_id"].value_counts().head())

print(master.groupby("company_id")["year"].unique().head())

company_id
PNB           300
POWERGRID      52
ADANIPORTS     52
ASIANPAINT     52
BAJAJ-AUTO     52
Name: count, dtype: int64
company_id
ABB           [2012, 2014, 2015, 2016, 2017, 2018, 2019, 202...
ADANIENSOL    [2014, 2015, 2016, 2017, 2018, 2019, 2020, 202...
ADANIENT      [2013, 2014, 2015, 2016, 2017, 2018, 2019, 202...
ADANIGREEN     [2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
ADANIPORTS    [2013, 2014, 2015, 2016, 2017, 2018, 2019, 202...
Name: year, dtype: object

In [51]:
print("Ratios")
print(ratios["year"].unique()[:10])

print("Market")
print(market["year"].unique()[:10])

print("ProfitLoss")
print(profitloss["year"].unique()[:10])

print("BalanceSheet")
print(balancesheet["year"].unique()[:10])

print("Cashflow")
print(cashflow["year"].unique()[:10])

Ratios
[2012 2014 2015 2016 2017 2018 2019 2020 2021 2022]
Market
[2019 2020 2021 2022 2023 2024]
ProfitLoss
[2012. 2014. 2015. 2016. 2017. 2018. 2019. 2020. 2021. 2022.]
BalanceSheet
[2012 2014 2015 2016 2017 2018 2019 2020 2021 2022]
Cashflow
[2013 2014 2015 2016 2017 2018 2019 2020 2021 2022]

In [52]:
print(ratios["year"].isna().sum())
print(market["year"].isna().sum())
print(profitloss["year"].isna().sum())
print(balancesheet["year"].isna().sum())
print(cashflow["year"].isna().sum())

0
0
100
0
0

In [53]:
print(profitloss["year"].head(20))
print(profitloss["year"].unique()[:20])

0     2012.0
1     2014.0
2     2015.0
3     2016.0
4     2017.0
5     2018.0
6     2019.0
7     2020.0
8     2021.0
9     2022.0
10    2023.0
11    2024.0
12       NaN
13    2014.0
14    2015.0
15    2016.0
16    2017.0
17    2018.0
18    2019.0
19    2020.0
Name: year, dtype: float64
[2012. 2014. 2015. 2016. 2017. 2018. 2019. 2020. 2021. 2022. 2023. 2024.
   nan 2013. 2011.]

In [54]:
import pandas as pd

ratios = pd.read_csv("data/processed/ratios.csv")
market = pd.read_csv("data/processed/market.csv")
profitloss = pd.read_csv("data/processed/profitloss.csv")
balancesheet = pd.read_csv("data/processed/balancesheet.csv")
cashflow = pd.read_csv("data/processed/cashflow.csv")

for df in [ratios, market, profitloss, balancesheet, cashflow]:
    df["year"] = pd.to_numeric(df["year"], errors="coerce")
    df = df[df["year"].notna()]
    df["year"] = df["year"].astype(int)

master = (
    ratios
    .merge(market, on=["company_id","year"], how="left")
    .merge(profitloss, on=["company_id","year"], how="left")
    .merge(balancesheet, on=["company_id","year"], how="left")
    .merge(cashflow, on=["company_id","year"], how="left")
)

master.to_csv("data/processed/master_dataset.csv", index=False)

FileNotFoundError: [Errno 2] No such file or directory: 'data/processed/ratios.csv'

In [55]:
find . -name "master_dataset.csv"

SyntaxError: invalid syntax (2272077001.py, line 1)